import type { Metadata } from "next";
import { Open_Sans, Manrope } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/common";
import { Hero, MiddleContent } from "./Home";

const open_Sans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
})

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${open_Sans.variable} ${manrope.variable} antialiased md:px-[100px] px-[18px]`}
      >
        <NavBar />
        <Hero />
        <MiddleContent />
        {children}
      </body>
    </html>
  );
}
